version: 0.2

env:
  variables:
    ARTIFACT_NAME: "myapp"  # 自定义应用名称
    OUTPUT_DIR: "output"

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - yum install -y maven

  build:
    commands:
      - mvn clean install
      - mkdir -p "${OUTPUT_DIR}"
      - cp target/*.war "${OUTPUT_DIR}/${ARTIFACT_NAME}.war"

artifacts:
  files:
    - "${OUTPUT_DIR}/*.war"
    - "appspec.yml"
    - "scripts/**/*"
  discard-paths: no  # 保留目录结构
