version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - mvn clean
  build:
    commands:
      - echo Build phase started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/simple-java-app-1.0-SNAPSHOT.jar
    - appspec.yml
    - scripts/**/*
  discard-paths: no
