version: 0.2
 phases:
 install:
 runtime-versions:
 java: corretto8
 commands:
 - yum install -y maven
 build:
 commands:
 - mvn clean install
 - mkdir output
 - cp target/*.war output/$APPLICATION_NAME.war
 artifacts:
 files:
 - 'output/*.war'
 - appspec.yml
 - scripts/*